apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ template "laravel.fullname" . }}-default
          env:
            - name: DB_HOST
              value: {{ include "laravel.databaseHost" . | quote }}
            - name: DB_PORT
              value: {{ include "laravel.databasePort" . | quote }}
            - name: DB_DATABASE
              value: {{ include "laravel.databaseName" . | quote }}
            - name: DB_USERNAME
              value: {{ include "laravel.databaseUser" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: {{ include "laravel.databaseSecretName" . }}
            - name: REDIS_HOST
              value: {{ include "laravel.redisHost" . | quote }}
            - name: REDIS_PORT
              value: {{ include "laravel.redisPort" . | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: {{ include "laravel.redisSecretName" . }}
            - name: MINIO_HOST
              value: {{ include "laravel.minioHost" . | quote }}
            - name: MINIO_PORT
              value: {{ include "laravel.minioPort" . | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access-key
                  name: {{ include "laravel.minioSecretName" . }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: {{ include "laravel.minioSecretName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
