{{- if not .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externalMinio" }}
type: Opaque
data:
  access-key: {{ .Values.externalMinio.accessKey | b64enc | quote }}
  secret-key: {{ .Values.externalMinio.secretKey | b64enc | quote }}
{{- end -}}
