{{- if not .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb" }}
type: Opaque
data:
  mysql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end -}}
